### ISSUE TITLE
Need Rust docs on `protocols::v2::subprotocols`

### ISSUE THREAD

**Issue by GitGab19** [stratum-mining/stratum#1201]
# Background
Currently, the `protocols::v2::subprotocols` has already been documented, but it's worth a look to see where to improve it. Since it contains 4 different crates, this issue is the tracker one, and more specific ones are going to be grouped here.

> Note: While this issue addresses the need for doc comments, it will also serve as a means to identify code debt that needs to be cleaned up and addressed in future issues.

# Solution
Navigate through each crate in `protocols::v2::subprotocols` and add:
- Rust Docs comments (following the formatting structure in [this on-going discussion](https://github.com/stratum-mining/stratum/discussions/970)), to be displayed in `docs.rs`
- a descriptive `README.md` file to be displayed in `crates.io`

While this work is being performed, specific code debt should be looked for and recorded to turn into future issues

# Task list
  - [x] `common_messages_sv2`: #1203 
  - [x] `job_declaration_sv2`: #1204 
  - [ ] `mining_sv2`: #1205 
  - [x] `template_distribution_sv2`: #1206

**Comment by plebhash** [comment]
closed via

- https://github.com/stratum-mining/stratum/pull/1242
- https://github.com/stratum-mining/stratum/pull/1265
- https://github.com/stratum-mining/stratum/pull/1243
- https://github.com/stratum-mining/stratum/pull/1257
