### ISSUE TITLE
MVP1 Translator Proxy/SV1 Protocol/SV1 MD TODOs + Thoughts

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#226]
- [x] #320 
- [x] #265
- [x] #266 
- [x] #318 
- [x] Pool never sends a new job after the initial connection. Something wrong with extended channels. Perhaps pool is never receiving the messages from the proxy? Logging would be a huge help here.
   Fixed with commit `4845829`
- [x] Update the Bitcoin Core TP fork and use with proxy
- [x] Remove useless loop [at end of `main` fn](https://github.com/rrybarczyk/stratum/blob/v1-s9-post-rebase/roles/translator/src/main.rs#L149)
- [x] Currently handling submits two times, just need to do it once [here](https://github.com/rrybarczyk/stratum/blob/v1-s9-post-rebase/roles/translator/src/main.rs#L107), no need to reinitialize it [here](https://github.com/rrybarczyk/stratum/blob/v1-s9-post-rebase/roles/translator/src/main.rs#L111)

**Comment by xraid** [comment]
mining.set_difficulty should let the pool/proxy decide to change the diff.

i know BraidPool will set difficult at miners to even out variance for smol miners
and is in favor using this repo to build on ...

**Comment by rrybarczyk** [comment]
Closed with #300
