### ISSUE TITLE
Stabilize SV1/SV2 Translator Proxy for MVP1

### ISSUE THREAD

**Issue by rrybarczyk** [stratum-mining/stratum#230]
# Stabilize SV1/SV2 Translator Proxy

- [x] stratum-mining/stratum#231
- [ ] stratum-mining/sri-docs#3
- [x] stratum-mining/stratum#93
