### ISSUE TITLE
Improve roles-logic-sv2 interface usability

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#48]
# Improve messages-sv2 interface usability

The crate [messages-sv2](https://github.com/stratum-mining/stratum/tree/main/protocols/v2/messages-sv2) that is a crate that stay between the low levels crates ([subprotocols](https://github.com/stratum-mining/stratum/tree/main/protocols/v2/subprotocols), [codec](https://github.com/stratum-mining/stratum/tree/main/protocols/v2/codec-sv2),
[noise](https://github.com/stratum-mining/stratum/tree/main/protocols/v2/noise-sv2), [binary](https://github.com/stratum-mining/stratum/tree/main/protocols/v2/binary-sv2), [framing](https://github.com/stratum-mining/stratum/tree/main/protocols/v2/framing-sv2)) and the [high level roles implementation](https://github.com/stratum-mining/stratum/tree/main/roles/v2) it export an interface that make some very
recurrent operation rather complex to execute. The exported interface should be refactored in order
to make this operations easier. (Performance must have priority on usability btw)

- [x] stratum-mining/stratum#66
- [x] stratum-mining/stratum#67
- [ ] stratum-mining/sri-docs#5
- [x] stratum-mining/stratum#69

**Comment by GitGab19** [comment]
Closing this as stale
