### ISSUE TITLE
Implement new message framing

### ISSUE THREAD

**Issue by pavlenex** [stratum-mining/stratum#546]
_Originally posted by @Fi3_ 

We need to implement the new framing proposed by @jakubtrnka Jakub (https://github.com/stratum-mining/sv2-spec/issues/31). To do this, we need to:

- [x] Add the PR in the specs, review and merge it 
- [x] Add new framing to the the SRI codebase
- [x] And  new framing to the the bitcoind codebase

 The old framing will no longer be supported.
__________

Tagging @jakubtrnka  @ccdle12 and @Fi3 since they'll be critical to leading this towards success. Jakub will need to create a PR for specs, then community needs to review it, even though concept ACK and consensus for this already exist, we need to concretize it in a form of a PR. Ccdle and Fi3 will be important for implementing this change, Fi3 in SRI, and ccdle12 in bitcoind.
