### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by Fi3** [stratum-mining/stratum#56]
# Add Documentation

- [ ] stratum-mining/stratum#108
- [ ] stratum-mining/stratum#57
- [ ] stratum-mining/stratum#59
- [ ] stratum-mining/stratum#109
- [ ] stratum-mining/stratum#110
- [ ] stratum-mining/sri-docs#1

**Comment by pavlenex** [comment]
Closing this tracker, since we're moving some of these if not all to the docs repo.
