### ISSUE TITLE
new Release

### ISSUE THREAD

**Issue by plebhash** [stratum-mining/stratum#880]
# todo

generate changelog

https://github.com/stratum-mining/stratum/blob/main/RELEASE.md#versioning

**Comment by pavlenex** [comment]
**High-prio**
These two are specs incompatibilities and should be addressed with a priority before pushing a new release:
- [ ] https://github.com/stratum-mining/stratum/issues/853
- [ ] https://github.com/stratum-mining/stratum/issues/860
- [ ] Changelog generation https://github.com/stratum-mining/stratum/blob/main/RELEASE.md#versioning

**Medium-prio,**
- [ ] https://github.com/stratum-mining/stratum/pull/867 (my understanding is this one will help with flaky tests
- https://github.com/stratum-mining/stratum/pull/833 (needs review by @lorbax)

**Low-prio**

Could be included to reduce backlog
- [ ] https://github.com/stratum-mining/stratum/pull/848
- [ ] https://github.com/stratum-mining/stratum/pull/866
- [ ] https://github.com/stratum-mining/stratum/pull/851 (needs @nikicat to push updates)

**Comment by plebhash** [comment]
@Fi3 suggested that we use this crate to check for versioning:

https://crates.io/crates/cargo-semver-checks
